### ISSUE TITLE
Post - Commit: to send e-mail notifications

### ISSUE THREAD

**Issue by MjAlmel** [jjthomas3/subhooker#9]
Hey!! I am not able to run your post-commit program to send e-mails after a commit. I have downloaded the zip file, but I can't find the "bin" folder with the main program. Could you help me please?
I am running in Windows Server 2008.

Thanks in advanced.

**Comment by jjthomas3** [comment]
I apologize, GIT didn't send me the usual e-mail alerting me of a new issue. When you extract the ZIP file it will create the following folder "subHooker-2.4.0\bin". So if you extracted the ZIP archive to C:\MySVNRepo\hooks then the BIN folder would be located at:  "C:\MySVNRepo\hooks\subHooker-2.4.0\bin" The BIN folder contains a BATCH file that you call to run Subhooker. SubHooker is written in Java so the BATCH file sets up the Java class path and everything.
